channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - tqdm
  - matplotlib
  - pandas
  - pip:
    - ase
    - ipi>=3.1.7,<4
    - metatomic-torch<=0.1.8 
    - metatrain
    - vesin>=0.4.2  
