channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - tqdm
  - matplotlib
  - pandas
  - pip:
    - ase
    - ipi>=3.1.7,<4
    - git+https://github.com/metatensor/metatrain.git
    - git+https://github.com/metatensor/metatomic.git
    - vesin>=0.5.0,<0.6.0  
