channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - ase>=3.24,<3.30
    - chemiscope>=0.8.5
    - matplotlib
    - metatensor
    - featomic
    - skmatter>=0.3
    - requests
