channels:
  - metatensor
  - conda-forge
  - https://repo.prefix.dev/rg-forge
dependencies:
  - eon>=2.9.0
  - ira
  - python=3.13
  - pip
  - uv
  - pip:
    - torch>=2.9,<2.10 
    - ase>=3.23
    - matplotlib
    - metatrain  
    - requests
    - rgpycrumbs>=0.1.3,<0.2
    - chemparseplot>=0.1.0,<0.2
