channels:
  - metatensor
  - conda-forge
  - https://repo.prefix.dev/rg-forge
dependencies:
  - eon>=2.9.0
  - ira
  - libtorch>=2.9,<2.10 
  - pip
  - python=3.13
  - uv
  - pip:
    - ase>=3.23
    - matplotlib
    - metatrain  
    - requests
    - rgpycrumbs>=0.1.2,<0.2
