channels:
  - metatensor
  - conda-forge
  - https://repo.prefix.dev/rg-forge
dependencies:
  - eon>=2.9.0
  - ira
  - python=3.13
  - pip
  - uv
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch>=2.9,<2.10 
    - ase>=3.23
    - matplotlib
    - metatrain  
    - requests
    - rgpycrumbs>=0.1.2,<0.2
variables:
  PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
