channels:
  - plumed/label/nightly
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - gfortran
  - make
  - git
  - plumed
  - py-plumed
  - pip:
    - ase>=3.23
    - chemiscope>=1.0
    - ipi>=3.1.5.1
    - matplotlib
variables:
  PYTHONPATH:
  PLUMED_KERNEL:
