channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - ase==3.22.1
    - chemiscope>=1.0
    - matplotlib
    - scipy
    - metatensor
    - featomic
    - scikit-learn
    - skmatter>=0.3
