channels:
  - metatensor
  - conda-forge
dependencies:
  - python=3.12
  - pip 
  - lammps-metatomic
  - pip:
    - ase>=3.23
    - pet-mad>=1.2.0,<2.0
    - ipi>=3.1.5,<4.0
    - chemiscope>=1.0
    - metatomic-torch>=0.1.2,<0.2
    - matplotlib>=3.10,<4.0
    - vesin>=0.4.2,<0.5
